"""Session-owned SCF results and optional post-SCF calculations."""
from pathlib import Path
import tempfile
import time

import numpy as np


def run_scf(settings):
    from pyfock import Basis, Mol, DFT

    with tempfile.TemporaryDirectory() as directory:
        xyz_path = Path(directory) / 'molecule.xyz'
        xyz_path.write_text(settings['xyz_content'])
        mol = Mol(coordfile=str(xyz_path))
        basis = Basis(mol, {'all': Basis.load(mol=mol, basis_name=settings['basis_set'])})
        if basis.bfs_nao > 120:
            raise ValueError(f'This system has {basis.bfs_nao} basis functions; the hosted limit is 120.')
        auxbasis = Basis(mol, {'all': Basis.load(mol=mol, basis_name=settings['auxbasis'])})
        dft = DFT(mol, basis, auxbasis, xc=settings['xc_functional'],
                  gridsLevel=settings['grid_level'], dmat_guess_method=settings['initial_guess'])
        dft.conv_crit = settings['conv_crit']
        dft.max_itr = settings['max_iterations']
        dft.ncores = settings['ncores']
        dft.save_ao_values = True
        dft.sao = settings['use_sao_basis']
        started = time.perf_counter()
        energy, dmat = dft.scf()
    return dict(settings=dict(settings), dft=dft, mol=mol, basis=basis,
                energy=energy, dmat=dmat, elapsed=time.perf_counter()-started,
                actions=[], cubes={}, forces=None, dipole=None, comparison=None, log='')


def calculate_forces(result):
    from pyfock import DFT_Grad
    return np.asarray(DFT_Grad(result['dft']).calculate()['forces'])


def calculate_dipole(result):
    from pyfock import Integrals
    integrals = Integrals.dipole_moment_mat_symm(result['basis'])
    return np.asarray(result['mol'].get_dipole_moment(integrals, result['dmat']))


def generate_cube(result, orbital, resolution):
    from pyfock import Utils
    mol, basis, dft = result['mol'], result['basis'], result['dft']
    with tempfile.TemporaryDirectory() as directory:
        path = str(Path(directory) / 'values.cube')
        options = dict(nx=resolution, ny=resolution, nz=resolution, ncores=result['settings']['ncores'])
        if orbital is None:
            Utils.write_density_cube(mol, basis, result['dmat'], path, **options)
        else:
            coefficients = dft.mo_coefficients[:, orbital]
            if dft.sao:
                coefficients = basis.cart2sph_basis().T @ coefficients
            Utils.write_orbital_cube(mol, basis, coefficients, path, **options)
        return Path(path).read_text()


def compare_energy(result, xc_mapping):
    from pyscf import gto, dft, scf
    s = result['settings']
    mol = gto.M(atom='\n'.join(s['xyz_content'].strip().splitlines()[2:]),
                basis=s['basis_set'], cart=not s['use_sao_basis'], verbose=4)
    if s['xc_functional'] == 'HF':
        mf = scf.RHF(mol).density_fit(auxbasis=s['auxbasis'])
    else:
        mf = dft.RKS(mol).density_fit(auxbasis=s['auxbasis'])
        mf.xc = xc_mapping[s['xc_functional']]
        mf.grids.level = s['grid_level']
    mf.conv_tol = s['conv_crit']
    mf.max_cycle = s['max_iterations']
    energy = mf.kernel(dm0=mf.init_guess_by_1e(mol))
    return dict(energy=energy, converged=mf.converged)


def build_input_script(result):
    s = result['settings']
    xyz_text = s['xyz_content'].strip().replace('\\', '\\\\').replace('"', '\\"')
    script = f'''# PyFock calculation generated by PyFock GUI
import os

# Set the CPU core count here; all thread settings below use this value.
ncores = {s['ncores']}

# Configure thread limits before importing PyFock and its numerical libraries.
os.environ["OMP_NUM_THREADS"] = str(ncores)
os.environ["OPENBLAS_NUM_THREADS"] = str(ncores)
os.environ["MKL_NUM_THREADS"] = str(ncores)
os.environ["VECLIB_MAXIMUM_THREADS"] = str(ncores)
os.environ["NUMEXPR_NUM_THREADS"] = str(ncores)

from pyfock import Basis, Mol, DFT

# XYZ coordinates
xyz_content = """
{xyz_text}
""".strip() + "\\n"

# Save XYZ to file
with open("molecule.xyz", "w") as handle:
    handle.write(xyz_content)

# Create the molecule from the XYZ coordinates.
mol = Mol(coordfile="molecule.xyz")
# Load the orbital basis for all atoms; it represents the molecular orbitals.
basis = Basis(mol, {{"all": Basis.load(mol=mol, basis_name={s['basis_set']!r})}})

# Load the auxiliary basis used to accelerate integrals through density fitting.
auxbasis = Basis(mol, {{"all": Basis.load(mol=mol, basis_name={s['auxbasis']!r})}})

# Create the DFT object with the chosen functional, native grid level, and initial guess.
dft = DFT(mol, basis, auxbasis, xc={s['xc_functional']!r},
          gridsLevel={s['grid_level']}, dmat_guess_method={s['initial_guess']!r})
dft.conv_crit = {s['conv_crit']!r}
dft.max_itr = {s['max_iterations']}
dft.ncores = ncores
dft.sao = {s['use_sao_basis']!r}
dft.save_ao_values = True

# Run SCF to obtain the total energy and density matrix.
energy, dmat = dft.scf()
print("Total energy (Ha):", energy)
'''
    for action in result['actions']:
        if action['kind'] == 'forces':
            script += '''\n# Forces from the converged SCF result
from pyfock import DFT_Grad
forces = DFT_Grad(dft).calculate()["forces"]
print("Forces (Ha/Bohr):", forces)
'''
        elif action['kind'] == 'dipole':
            script += '''\n# Dipole from the existing density matrix
from pyfock import Integrals
dipole_matrix = Integrals.dipole_moment_mat_symm(basis)
dipole = mol.get_dipole_moment(dipole_matrix, dmat)
print("Dipole (Debye):", dipole * 2.541746473)
'''
        elif action['kind'] == 'cube':
            orbital, resolution = action['orbital'], action['resolution']
            script += '\nfrom pyfock import Utils\n'
            if orbital is None:
                script += f'Utils.write_density_cube(mol, basis, dmat, "density_{resolution}.cube", nx={resolution}, ny={resolution}, nz={resolution}, ncores=dft.ncores)\n'
            else:
                script += f'''coefficients = dft.mo_coefficients[:, {orbital}]
if dft.sao:
    coefficients = basis.cart2sph_basis().T @ coefficients
Utils.write_orbital_cube(mol, basis, coefficients, "MO_{orbital}_{resolution}.cube", nx={resolution}, ny={resolution}, nz={resolution}, ncores=dft.ncores)
'''
        elif action['kind'] == 'comparison':
            script += f'''\n# Optional PySCF energy reference (core initial guess)
from pyscf import gto, dft as pyscf_dft, scf
reference_mol = gto.M(atom="molecule.xyz", basis={s['basis_set']!r}, cart={not s['use_sao_basis']!r})
'''
            if s['xc_functional'] == 'HF':
                script += f'mf = scf.RHF(reference_mol).density_fit(auxbasis={s["auxbasis"]!r})\n'
            else:
                script += f'mf = pyscf_dft.RKS(reference_mol).density_fit(auxbasis={s["auxbasis"]!r})\nmf.xc = {action["xc"]!r}\nmf.grids.level = {s["grid_level"]}\n'
            script += f'mf.conv_tol = {s["conv_crit"]!r}\nmf.max_cycle = {s["max_iterations"]}\nprint("PySCF energy (Ha):", mf.kernel(dm0=mf.init_guess_by_1e(reference_mol)))\n'
    return script
