"""Reusable helpers for the Streamlit geometry-optimization page."""

from io import StringIO

import numpy as np
from ase.calculators.singlepoint import SinglePointCalculator
from ase.io import write as ase_write
from ase.optimize import (
    BFGS,
    BFGSLineSearch,
    FIRE,
    FIRE2,
    GPMin,
    LBFGS,
    LBFGSLineSearch,
    MDMin,
    ODE12r,
)


MAX_OPTIMIZATION_CYCLES = 10

OPTIMIZERS = {
    "BFGS": BFGS,
    "BFGSLineSearch": BFGSLineSearch,
    "LBFGS": LBFGS,
    "LBFGSLineSearch": LBFGSLineSearch,
    "FIRE": FIRE,
    "FIRE2": FIRE2,
    "GPMin": GPMin,
    "MDMin": MDMin,
    "ODE12r": ODE12r,
}

OPTIMIZER_HELP = {
    "BFGS": "Full-memory quasi-Newton optimizer; a dependable choice for small molecules.",
    "BFGSLineSearch": "BFGS with a line search; may require extra energy and force evaluations.",
    "LBFGS": "Limited-memory BFGS; the recommended general-purpose default.",
    "LBFGSLineSearch": "Limited-memory BFGS with a line search.",
    "FIRE": "Damped-dynamics optimizer that is often robust for rough starting geometries.",
    "FIRE2": "ASE's newer FIRE variant with improved integration behavior.",
    "GPMin": "Gaussian-process optimizer intended mainly for small systems.",
    "MDMin": "Simple damped molecular-dynamics minimizer.",
    "ODE12r": "Adaptive ODE-based optimizer with automatic step-size control.",
}


def maximum_force(forces):
    """Return ASE's usual maximum per-atom force norm in eV/Angstrom."""
    force_array = np.asarray(forces, dtype=float)
    if force_array.size == 0:
        return 0.0
    return float(np.linalg.norm(force_array, axis=1).max())


def snapshot_with_results(atoms):
    """Copy an Atoms object and freeze its current energy and forces on the copy."""
    energy = float(atoms.get_potential_energy())
    forces = np.asarray(atoms.get_forces(), dtype=float).copy()
    frame = atoms.copy()
    frame.calc = SinglePointCalculator(frame, energy=energy, forces=forces)
    return frame, energy, forces


def frames_to_extxyz(frames):
    """Serialize ASE frames to extXYZ, including calculator energy and forces."""
    if not frames:
        raise ValueError("At least one trajectory frame is required.")
    buffer = StringIO()
    ase_write(buffer, frames, format="extxyz", write_results=True)
    return buffer.getvalue()


def atoms_to_xyz(atoms):
    """Serialize an ASE Atoms object to ordinary XYZ."""
    buffer = StringIO()
    ase_write(buffer, atoms, format="xyz")
    return buffer.getvalue()


def build_reproduction_script(
    xyz_content,
    optimizer_name,
    force_convergence,
    functional,
    basis_set,
    auxiliary_basis,
    scf_convergence,
    scf_max_iterations,
    use_sao_basis,
    grid_level,
    initial_guess,
    ncores=1,
    max_cycles=MAX_OPTIMIZATION_CYCLES,
):
    """Build a standalone PyFock + ASE script matching the page settings."""
    if optimizer_name not in OPTIMIZERS:
        raise ValueError("Unsupported optimizer: %s" % optimizer_name)

    xyz_text = xyz_content.strip().replace('\\', '\\\\').replace('"', '\\"')
    use_density_fitting = functional != "HF"
    return f'''# PyFock geometry optimization generated by PyFock GUI
import os

# Set the CPU core count before importing numerical libraries.
ncores = {int(ncores)}
for variable in (
    "OMP_NUM_THREADS",
    "OPENBLAS_NUM_THREADS",
    "MKL_NUM_THREADS",
    "VECLIB_MAXIMUM_THREADS",
    "NUMEXPR_NUM_THREADS",
):
    os.environ[variable] = str(ncores)

from ase.io import read, write
from ase.optimize import {optimizer_name}
from pyfock import PyFockCalculator

# XYZ coordinates
xyz_content = """
{xyz_text}
""".strip() + "\\n"
with open("molecule.xyz", "w", encoding="utf-8") as handle:
    handle.write(xyz_content)

# Create the ASE molecule from the XYZ coordinates.
atoms = read("molecule.xyz")

# Attach PyFock with the orbital basis, auxiliary density-fitting basis,
# functional, native grid level, and initial guess used for each SCF calculation.
atoms.calc = PyFockCalculator(
    functional={functional!r},
    basis={basis_set!r},
    auxbasis={auxiliary_basis!r},
    charge=0,
    ncores=ncores,
    DF={use_density_fitting!r},
    save_ao_values=True,
    sao={bool(use_sao_basis)!r},
    conv_crit={float(scf_convergence)!r},
    max_itr={int(scf_max_iterations)},
    gridsLevel={int(grid_level)},
    dmat_guess_method={initial_guess!r},
    directory="pyfock_geometry_optimization",
)

optimizer = {optimizer_name}(
    atoms,
    trajectory="optimization.traj",
    logfile="optimization.log",
)
converged = optimizer.run(
    fmax={float(force_convergence)!r},
    steps={int(max_cycles)},  # Increase this freely when running locally.
)

trajectory = read("optimization.traj", index=":")
write("optimization_trajectory.extxyz", trajectory, format="extxyz")
write("optimized_geometry.extxyz", atoms, format="extxyz")

print("Converged:", converged)
print("Optimization cycles:", optimizer.get_number_of_steps())
print("Final energy (eV):", atoms.get_potential_energy())
print("Final maximum force (eV/Angstrom):", max(
    (force**2).sum()**0.5 for force in atoms.get_forces()
))
'''
